### PR TITLE
Feature/fix test errors place

### PR DESCRIPTION
**Pull request by julia-rom**
### Description (Proposed changes, additional context, chosen approach/alternative approaches, gotchas, etc)

- All tests in `place.test.ts` were previously failing. This was mainly due to inconsistencies in the mock data (in `presenterPlace.ts`) after all of the data structure updates.  
- two of the tests were failing because they used taxonomy.SYSTEMS which doesn't currently exist. I removed this from the existing tests, and replaced it with a different taxonomy category (PURPOSE, for example). I also added a test expected data result to replace the old one for SYSTEMS. 
- general code clean up in test files (no unused vars or mock data). 

### Steps for reviewer(s) to reproduce/test

- ensure all tests are currently passing, that there are no data structure discrepancies.

### CODE REVIEW

**Review by tonybennett — CHANGES_REQUESTED** [review]
There is a type error, so the build is failing

Also not formatted with Prettier

Please run/pass `yarn lint` and `yarn format` and make sure it deploys before refreshing review

**Comment by julia-rom** [comment]
yes this is actually blocked at the moment (the type error). this is due to the firebase db not being up to date with data structure updates. Needs to be cleaned up first - so maybe this pr should be on pause

**Comment by julia-rom** [comment]
build should be ok now! had to remove two properties from the test Sensors data (email, phone) as they were moved to the Places model

**Review by tonybennett — COMMENTED** [review]
Seems good to me, @BeatriceDuncan or @turnKei want to give final ok?

The tests are probably a good use case for snapshots, but I guess better to follow existing work than create new work

**Review by turnKei — APPROVED** [review]

**Comment by julia-rom** [comment]
just needs your approval and can merge in @tonybennett

**Review by tonybennett — APPROVED** [review]
Sorry didn't realize I needed to approve if someone else did

**Pull request merged**
