### PR TITLE
Removes Typography per Jackie's request

### PR DESCRIPTION
**Pull request by BeatriceDuncan**
### Notion card link(s)

- [React: Add privacy policy link in footer](https://www.notion.so/normative/React-Add-privacy-policy-link-in-footer-945d6828bfdc49fcb05835a32a615c5b);

### Description (Proposed changes, additional context, chosen approach/alternative approaches, gotchas, etc)

- Jackie just asked for minor tweaks - see comments in notion card. 

### Steps for reviewer(s) to reproduce/test

- Just take a look at the footer for [Boston](https://dtpr-sticker-feature-co-yqww3c.herokuapp.com/places/lK7pio6ro) (no privacy policy) & [Normative](https://dtpr-sticker-feature-co-yqww3c.herokuapp.com/places/Ur-FM0fJw) (has privacy policy dummy link to Normative's website).

### CODE REVIEW

**Comment by turnKei** [comment]
Looks like maybe a different style being applied to Terms of use
Screen Shot 2021-10-21 at 9 30 50 AM

**Comment by BeatriceDuncan** [comment]
> Looks like maybe a different style being applied to Terms of use Screen Shot 2021-10-21 at 9 30 50 AM

Nice catch, I overlooked this as visited links. Fixed now.

**Comment by turnKei** [comment]
Looks good from a functionality perspective. @tonybennett How are you feeling

**Comment by tonybennett** [comment]
Seems like mostly content changes so no feedback

Although I like that the periods are no longer in the links 😍

**Pull request merged**
