### PR TITLE
Adds icons placeholders and place QRCode print

### PR DESCRIPTION
**Pull request by mbarragana**
# Notion card link(s)
- [Add placeholder to missing sensor and taxonomy icons](https://www.notion.so/normative/Add-placeholder-to-missing-sensor-and-taxonomy-icons-9f01db6aa0fe4382994bd5c7355f5097)

# Review APP
- [Heroku Review App](https://dtpr-sticker-feature-ic-spnfdx.herokuapp.com/sensors/myd2vKdzrsn7RaF4t_UIb)

# PR Description (Proposed changes, approach, gotchas, etc)
- [x] Adds icons placeholders
- [x] Adds place QRCode url link to be printed

# How to test it
- Access Review App through the link on the top of description and check feedback questions
- Check if icons are ok, according [Figma](https://www.figma.com/file/t1ZIjYmejw3bNc9hxMNzGB/Helpful-Places---Working-File?node-id=114%3A3482)
- Check if QRCode is show correctly with link

### CODE REVIEW

**Comment by turnKei** [comment]
Expected data process icon to show, shows blank: https://dtpr-sticker-feature-ic-spnfdx.herokuapp.com/sensors/slcJ3Jk93uilfXcZaOqhG

**Comment by turnKei** [comment]
I would expect the .zip to contain both QR codes SVGs, 2 complete pngs and one white hexagon SVG. Not seeing that
Screen Shot 2021-02-23 at 2 45 02 PM

**Comment by turnKei** [comment]
Looks like the PNGs are not being exported. The list should be every element needed to make the sign, + a png of the collection as it appears on screen.
Screen Shot 2021-02-24 at 9 54 50 AM

**Comment by turnKei** [comment]
Also looks to be missing organization, which in this case had no unique icon and used the placeholder. Should print what is shown in /sensor

**Comment by mbarragana** [comment]
> Also looks to be missing organization, which in this case had no unique icon and used the placeholder. Should print what is shown in /sensor

In this case it does not display neither download organization because it is missing logo probably

**Pull request merged**
